name = "social-os"
compatibility_date = "2026-06-01"
pages_build_output_dir = "./client/dist"

[[d1_databases]]
binding = "DB"
database_name = "we-aigo-db"
database_id = "be04d021-3769-4ca5-91c8-196056621490"

[env.production]
name = "social-os"

[[env.production.d1_databases]]
binding = "DB"
database_name = "we-aigo-db"
database_id = "be04d021-3769-4ca5-91c8-196056621490"
